/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as OurStoryRouteImport } from './routes/our-story'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as MediaRouteImport } from './routes/media'
import { Route as LocationsRouteImport } from './routes/locations'
import { Route as FranchiseRouteImport } from './routes/franchise'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CateringRouteImport } from './routes/catering'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const OurStoryRoute = OurStoryRouteImport.update({
  id: '/our-story',
  path: '/our-story',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const FranchiseRoute = FranchiseRouteImport.update({
  id: '/franchise',
  path: '/franchise',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CateringRoute = CateringRouteImport.update({
  id: '/catering',
  path: '/catering',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/careers': typeof CareersRoute
  '/catering': typeof CateringRoute
  '/contact': typeof ContactRoute
  '/franchise': typeof FranchiseRoute
  '/locations': typeof LocationsRoute
  '/media': typeof MediaRoute
  '/menu': typeof MenuRoute
  '/our-story': typeof OurStoryRoute
  '/rewards': typeof RewardsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/careers': typeof CareersRoute
  '/catering': typeof CateringRoute
  '/contact': typeof ContactRoute
  '/franchise': typeof FranchiseRoute
  '/locations': typeof LocationsRoute
  '/media': typeof MediaRoute
  '/menu': typeof MenuRoute
  '/our-story': typeof OurStoryRoute
  '/rewards': typeof RewardsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/careers': typeof CareersRoute
  '/catering': typeof CateringRoute
  '/contact': typeof ContactRoute
  '/franchise': typeof FranchiseRoute
  '/locations': typeof LocationsRoute
  '/media': typeof MediaRoute
  '/menu': typeof MenuRoute
  '/our-story': typeof OurStoryRoute
  '/rewards': typeof RewardsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/careers'
    | '/catering'
    | '/contact'
    | '/franchise'
    | '/locations'
    | '/media'
    | '/menu'
    | '/our-story'
    | '/rewards'
    | '/sitemap.xml'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/careers'
    | '/catering'
    | '/contact'
    | '/franchise'
    | '/locations'
    | '/media'
    | '/menu'
    | '/our-story'
    | '/rewards'
    | '/sitemap.xml'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/careers'
    | '/catering'
    | '/contact'
    | '/franchise'
    | '/locations'
    | '/media'
    | '/menu'
    | '/our-story'
    | '/rewards'
    | '/sitemap.xml'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CareersRoute: typeof CareersRoute
  CateringRoute: typeof CateringRoute
  ContactRoute: typeof ContactRoute
  FranchiseRoute: typeof FranchiseRoute
  LocationsRoute: typeof LocationsRoute
  MediaRoute: typeof MediaRoute
  MenuRoute: typeof MenuRoute
  OurStoryRoute: typeof OurStoryRoute
  RewardsRoute: typeof RewardsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-story': {
      id: '/our-story'
      path: '/our-story'
      fullPath: '/our-story'
      preLoaderRoute: typeof OurStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/franchise': {
      id: '/franchise'
      path: '/franchise'
      fullPath: '/franchise'
      preLoaderRoute: typeof FranchiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catering': {
      id: '/catering'
      path: '/catering'
      fullPath: '/catering'
      preLoaderRoute: typeof CateringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CareersRoute: CareersRoute,
  CateringRoute: CateringRoute,
  ContactRoute: ContactRoute,
  FranchiseRoute: FranchiseRoute,
  LocationsRoute: LocationsRoute,
  MediaRoute: MediaRoute,
  MenuRoute: MenuRoute,
  OurStoryRoute: OurStoryRoute,
  RewardsRoute: RewardsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
